DROP TABLE COMMENTS;
DROP TABLE ADMINS;
DROP TABLE USERS;
DROP TABLE NEWS_POST;
DROP TABLE OPINION_POST;
DROP TABLE POST;

CREATE DATABASE JordanAndersonBlog;


CREATE TABLE POST (
	POSTID int NOT NULL,
	TITLE VARCHAR(50),
	CONTENT VARCHAR(2000),
	CONSTRAINT pk_POSTID PRIMARY KEY (POSTID)
)

CREATE TABLE OPINION_POST (
	OPINION_POSTID int NOT NULL,
	POSTID int NOT NULL,
	CONSTRAINT pk_OPINIONPOSTID PRIMARY KEY (OPINION_POSTID),
	CONSTRAINT fk_POSTID_OP FOREIGN KEY (POSTID)
)

CREATE TABLE NEWS_POST (
	NEW_POSTID int NOT NULL,
	POSTID int NOT NULL,
	CONSTRAINT pk_NEWSPOSTID PRIMARY KEY (NEWS_POSTID),
	CONSTRAINT fk_POSTID_NP FOREIGN KEY (POSTID) REFERENCES POST(pk_POSTID)
)

CREATE TABLE USERS (
	USERID int NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	FNAME VARCHAR(25) NOT NULL,
	LNAME VARCHAR(25) NOT NULL,
	CONSTRAINT pk_USERS_USERID PRIMARY KEY (USERID)
)

CREATE TABLE ADMINS (
	ADMIN_ID int NOT NULL,
	USERID int NOT NULL ,
	CONSTRAINT pk_ADMINS_ADMIN_ID PRIMARY KEY (ADMIN_ID),
	CONSTRAINT fk_ADMINS_USERID FOREIGN KEY (USERID) REFERENCES USERS(pk_USERS_USERID)
)

CREATE TABLE COMMENTS (
	COMMENT_ID int NOT NULL,
	CONTENT VARCHAR(250) NOT NULL,
	TITLE VARCHAR(25),
	CONSTRAINT pk_COMMENTS_COMMENTID PRIMARY KEY (COMMENT_ID)
)
